name: knpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python <3.14
  - numpy
  - scipy
  - matplotlib
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - pytest
  - pytest-mock
  - pytest-cov
  - packaging
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - seaborn
  - click
  - orix >=0.13
  - scikit-image
  - networkx
  - jsonschema

