name: knpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy<=2.2.6
  - scipy
  - matplotlib
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - pytest
  - pytest-mock
  - pytest-cov
  - packaging
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - seaborn
  - click
  - orix>=0.13
  - scikit-image
  - networkx
  - jsonschema
